image: maven:latest

# 本次构建的阶段：build package
stages:
  - build
  - package
# 构建 Job
build:
  stage: build
  tags:
    - test
  script:
    - echo "=============== 开始编译构建任务 ==============="
    - mvn compile
# 打包
package:
  stage: package
  tags:
    - test
  script:
    - echo "=============== 开始打包任务  ==============="
    - mvn clean package -Dmaven.test.skip=true